"""initial_schema

Revision ID: 10e4fac5e5d4
Revises: 
Create Date: 2026-01-23 01:20:38.153525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e4fac5e5d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_ntn', sa.String(length=13), nullable=False, comment='Seller National Tax Number (13 digits)'),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('fbr_token', sa.Text(), nullable=True, comment='FBR Bearer token (user-provided for MVP)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_seller_ntn'), 'tenants', ['seller_ntn'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_ref_no', sa.String(length=50), nullable=False, comment='Unique invoice reference number per tenant'),
    sa.Column('invoice_type', sa.Enum('SALE', 'DEBIT', 'CREDIT', name='invoicetype'), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('referenced_invoice_id', sa.Uuid(), nullable=True, comment='Reference to original Sales Invoice (for debit/credit notes)'),
    sa.Column('buyer_ntn_cnic', sa.String(length=13), nullable=False, comment='Buyer NTN or CNIC'),
    sa.Column('buyer_business_name', sa.String(length=255), nullable=False),
    sa.Column('buyer_province', sa.String(length=100), nullable=False),
    sa.Column('buyer_address', sa.Text(), nullable=False),
    sa.Column('buyer_registration_type', sa.Enum('REGISTERED', 'UNREGISTERED', name='buyerregistrationtype'), nullable=False),
    sa.Column('scenario_id', sa.String(length=10), nullable=False, comment='FBR scenario ID'),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'FAILED', 'UNKNOWN', name='invoicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['referenced_invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'invoice_ref_no', name='uq_tenant_invoice_ref')
    )
    op.create_index(op.f('ix_invoices_invoice_ref_no'), 'invoices', ['invoice_ref_no'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('hs_code', sa.String(length=20), nullable=False, comment='Harmonized System code (e.g., 0000.0000)'),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('rate', sa.String(length=10), nullable=False, comment="Tax rate (e.g., '0%', '17%')"),
    sa.Column('uom', sa.String(length=20), nullable=False, comment='Unit of Measure'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_values', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('value_sales_excluding_st', sa.Numeric(precision=18, scale=2), nullable=False, comment='Value of sales excluding Sales Tax'),
    sa.Column('fixed_notified_value', sa.Numeric(precision=18, scale=2), nullable=False, comment='Fixed/Notified value or Retail Price'),
    sa.Column('sales_tax_applicable', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sales_tax_withheld', sa.Numeric(precision=18, scale=2), nullable=False, comment='Sales Tax withheld at source'),
    sa.Column('extra_tax', sa.String(length=50), nullable=False),
    sa.Column('further_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sro_schedule_no', sa.String(length=50), nullable=False, comment='SRO Schedule Number'),
    sa.Column('fed_payable', sa.Numeric(precision=18, scale=2), nullable=False, comment='Federal Excise Duty payable'),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sale_type', sa.String(length=50), nullable=False),
    sa.Column('sro_item_serial_no', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('submission_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False, comment='Sequential attempt number for this invoice'),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False, comment='FBR endpoint URL used'),
    sa.Column('http_status', sa.Integer(), nullable=True, comment='HTTP status code (null if timeout/network error)'),
    sa.Column('outcome', sa.Enum('SUCCESS', 'VALIDATION_ERROR', 'AUTH_ERROR', 'TIMEOUT', 'NETWORK_ERROR', 'UNKNOWN', name='submissionoutcome'), nullable=False),
    sa.Column('diagnostic_id', sa.String(length=50), nullable=False, comment='Unique ID for support reference'),
    sa.Column('response_summary', sa.Text(), nullable=False, comment='Sanitized response summary (no sensitive data)'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='Response time in milliseconds'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_attempts_invoice_id'), 'submission_attempts', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_attempts_invoice_id'), table_name='submission_attempts')
    op.drop_table('submission_attempts')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_ref_no'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_tenants_seller_ntn'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
